export const circularProgressBar: string;
export const green: string;
export const red: string;
export const amber: string;
export const circularProgressBarTrail: string;
export const circularProgressBarText: string;
export const circularProgressBarBackground: string;
export const circularProgressBarInverted: string;
export const circularProgressBarPath: string;
