export const iconLink: string;
export const badge: string;
export const badgeCount: string;
export const primary: string;
export const secondary: string;
export const info: string;
export const success: string;
export const warning: string;
export const danger: string;
