export const expandableNavLink: string;
export const dropDown: string;
export const mini: string;
export const growIn: string;
export const expanded: string;
export const hidden: string;
export const link: string;
export const clickableLink: string;
export const chevron: string;
